const fs = require('fs');
const path = require('path');

// Path to the IDL file generated by Anchor
const idlPath = path.join(__dirname, '../solana-program/target/idl/omnivault.json');
const outputPath = path.join(__dirname, '../frontend/src/idl/omnivault.ts');

// Read the IDL JSON file
try {
  if (!fs.existsSync(idlPath)) {
    console.error(`IDL file not found at ${idlPath}`);
    console.error('Please run "anchor build" first to generate the IDL');
    process.exit(1);
  }

  const idlJson = fs.readFileSync(idlPath, 'utf8');
  const idl = JSON.parse(idlJson);
  
  // Create TypeScript file content
  const tsContent = `// This file is auto-generated from the IDL
// Do not edit manually

export type OmnivaultIDL = ${JSON.stringify(idl, null, 2)};

export const OmnivaultIDL: OmnivaultIDL = ${JSON.stringify(idl, null, 2)};
`;

  // Create the output directory if it doesn't exist
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write the TypeScript file
  fs.writeFileSync(outputPath, tsContent);
  console.log(`✅ IDL TypeScript file generated at ${outputPath}`);
  console.log(`📋 Program ID: ${idl.metadata?.address || 'Not found'}`);
  console.log(`🏗️  Instructions: ${idl.instructions?.length || 0}`);
  console.log(`📊 Accounts: ${idl.accounts?.length || 0}`);
} catch (error) {
  console.error('❌ Error generating IDL TypeScript file:', error.message);
  process.exit(1);
} 